apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ioraw6tkq-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/ioraw6tkq-java-quarkus-gitops